version: 2.1

# Define the jobs we want to run for this project
jobs:
    build:
        docker:
          - image: circleci/python:3.7.10
        working_directory: ~/repo
        steps:
          - checkout
          - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "requirements.txt" }}
                    - v1-dependencies-
          - run: 
                name: install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
          - save_cache:
                paths:
                    - ./venv
                key: v1-dependencies-{{ checksum "requirements.txt" }}
    test:
        docker:
            - image: circleci/python:3.7.10
    
        steps:
            - checkout
            - lint: 
                name: run lint
                command: |
                    . venv/bin/activate
                    make lint
            - run: 
                name: run tests
                command: |
                    . venv/bin/activate
                    make test
